language: go
sudo: required
services:
  - docker
go:
  - 1.8
os:
  - linux
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip
  - pip install -r tests/requirements.txt
  - docker pull minio/minio
  - docker pull ubuntu
install:
  - make depends
  - make
script: 
  - make lint
  - make test
notifications:
  email: false
