language: go
sudo: required
services:
  - docker
go:
  - 1.8
os:
  - linux
before_install:
  - docker pull minio/minio
install:
  - make depends
  - make
script: 
  - make lint
  - make test
notifications:
  email: false
