os:
  - linux
language: go
sudo: required
services:
  - docker
cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg
    - vendor
go:
  - 1.8
install:
  - make depends
  - make
jobs:
  include:
    - stage: lint
      script: make lint
    - stage: test
      script: make test
    - script: make test-backends
    - script: make test-elasticsearch
    - script: make test-mongodb
    - script: make test-kafka

notifications:
  email: false
