os:
  - linux
language: go
sudo: required
services:
  - docker
cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg
    - vendor
go:
  - 1.8
before_install:
  - docker pull ohsucompbio/htcondor
  - docker pull ohsucompbio/slurm
  - docker pull ohsucompbio/gridengine
  - docker pull ohsucompbio/pbs-torque
  - docker pull docker.elastic.co/elasticsearch/elasticsearch:5.6.3
  - docker pull mongo:3.5.13
install:
  - make depends
  - make
jobs:
  include:
    - stage: lint
      script: make lint
    - stage: test
      script: make test
    - script: make test-backends
    - script: make test-elasticsearch
    - script: make test-mongodb
    - script: make test-kafka

notifications:
  email: false
