Server:
  HostName: funnel-server
Backend: manual
Scheduler:
  Node:
    ServerAddress: funnel-server:9090
Worker:
  ServerAddress: funnel-server:9090
  Storage:
    Local:
      AllowedDirs:
        - /opt/cwl
    GS:
      - FromEnv: true
