package mocks

import dts "github.com/ohsu-comp-bio/funnel/ccc/dts"
import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetFile provides a mock function with given fields: id
func (_m *Client) GetFile(id string) (*dts.Entry, error) {
	ret := _m.Called(id)

	var r0 *dts.Entry
	if rf, ok := ret.Get(0).(func(string) *dts.Entry); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dts.Entry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
