// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

/*
Package events is a generated protocol buffer package.

It is generated from these files:
	events.proto

It has these top-level messages:
	SystemLog
	Event
	CreateEventResponse
*/
package events

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import tes "github.com/ohsu-comp-bio/funnel/proto/tes"
import google_protobuf1 "github.com/golang/protobuf/ptypes/struct"
import google_protobuf2 "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Type int32

const (
	Type_UNKNOWN             Type = 0
	Type_STATE               Type = 1
	Type_START_TIME          Type = 2
	Type_END_TIME            Type = 3
	Type_OUTPUTS             Type = 4
	Type_METADATA            Type = 5
	Type_EXECUTOR_START_TIME Type = 6
	Type_EXECUTOR_END_TIME   Type = 7
	Type_EXIT_CODE           Type = 8
	Type_HOST_IP             Type = 9
	Type_PORTS               Type = 10
	Type_STDOUT              Type = 11
	Type_STDERR              Type = 12
	Type_SYSLOG              Type = 13
)

var Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "STATE",
	2:  "START_TIME",
	3:  "END_TIME",
	4:  "OUTPUTS",
	5:  "METADATA",
	6:  "EXECUTOR_START_TIME",
	7:  "EXECUTOR_END_TIME",
	8:  "EXIT_CODE",
	9:  "HOST_IP",
	10: "PORTS",
	11: "STDOUT",
	12: "STDERR",
	13: "SYSLOG",
}
var Type_value = map[string]int32{
	"UNKNOWN":             0,
	"STATE":               1,
	"START_TIME":          2,
	"END_TIME":            3,
	"OUTPUTS":             4,
	"METADATA":            5,
	"EXECUTOR_START_TIME": 6,
	"EXECUTOR_END_TIME":   7,
	"EXIT_CODE":           8,
	"HOST_IP":             9,
	"PORTS":               10,
	"STDOUT":              11,
	"STDERR":              12,
	"SYSLOG":              13,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SystemLog struct {
	Msg    string                   `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	Level  uint32                   `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	Fields *google_protobuf1.Struct `protobuf:"bytes,3,opt,name=fields" json:"fields,omitempty"`
}

func (m *SystemLog) Reset()                    { *m = SystemLog{} }
func (m *SystemLog) String() string            { return proto.CompactTextString(m) }
func (*SystemLog) ProtoMessage()               {}
func (*SystemLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SystemLog) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SystemLog) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *SystemLog) GetFields() *google_protobuf1.Struct {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Event struct {
	// Event type
	Type Type `protobuf:"varint,1,opt,name=type,enum=events.Type" json:"type,omitempty"`
	// Task ID
	Id string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	// Task attempt ID
	Attempt uint32 `protobuf:"varint,3,opt,name=attempt" json:"attempt,omitempty"`
	// Event timestamp
	Timestamp *google_protobuf2.Timestamp `protobuf:"bytes,4,opt,name=timestamp" json:"timestamp,omitempty"`
	// Task event fields:
	// Only one field is set per event type.
	State     tes.State                   `protobuf:"varint,5,opt,name=state,enum=tes.State" json:"state,omitempty"`
	StartTime *google_protobuf2.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime   *google_protobuf2.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	Outputs   []*tes.OutputFileLog        `protobuf:"bytes,8,rep,name=outputs" json:"outputs,omitempty"`
	Metadata  map[string]string           `protobuf:"bytes,9,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Executor events:
	// index is always set for executor events.
	Index uint32 `protobuf:"varint,10,opt,name=index" json:"index,omitempty"`
	// Only one field is set per executor event type.
	ExecutorStartTime *google_protobuf2.Timestamp `protobuf:"bytes,11,opt,name=executor_start_time,json=executorStartTime" json:"executor_start_time,omitempty"`
	ExecutorEndTime   *google_protobuf2.Timestamp `protobuf:"bytes,12,opt,name=executor_end_time,json=executorEndTime" json:"executor_end_time,omitempty"`
	ExitCode          int32                       `protobuf:"varint,13,opt,name=exit_code,json=exitCode" json:"exit_code,omitempty"`
	HostIp            string                      `protobuf:"bytes,14,opt,name=host_ip,json=hostIp" json:"host_ip,omitempty"`
	Ports             []*tes.Ports                `protobuf:"bytes,15,rep,name=ports" json:"ports,omitempty"`
	Stdout            string                      `protobuf:"bytes,16,opt,name=stdout" json:"stdout,omitempty"`
	Stderr            string                      `protobuf:"bytes,17,opt,name=stderr" json:"stderr,omitempty"`
	// System events:
	SystemLog *SystemLog `protobuf:"bytes,18,opt,name=system_log,json=systemLog" json:"system_log,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_UNKNOWN
}

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetAttempt() uint32 {
	if m != nil {
		return m.Attempt
	}
	return 0
}

func (m *Event) GetTimestamp() *google_protobuf2.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Event) GetState() tes.State {
	if m != nil {
		return m.State
	}
	return tes.State_UNKNOWN
}

func (m *Event) GetStartTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Event) GetEndTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *Event) GetOutputs() []*tes.OutputFileLog {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *Event) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Event) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Event) GetExecutorStartTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.ExecutorStartTime
	}
	return nil
}

func (m *Event) GetExecutorEndTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.ExecutorEndTime
	}
	return nil
}

func (m *Event) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *Event) GetHostIp() string {
	if m != nil {
		return m.HostIp
	}
	return ""
}

func (m *Event) GetPorts() []*tes.Ports {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *Event) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *Event) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

func (m *Event) GetSystemLog() *SystemLog {
	if m != nil {
		return m.SystemLog
	}
	return nil
}

type CreateEventResponse struct {
}

func (m *CreateEventResponse) Reset()                    { *m = CreateEventResponse{} }
func (m *CreateEventResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateEventResponse) ProtoMessage()               {}
func (*CreateEventResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*SystemLog)(nil), "events.SystemLog")
	proto.RegisterType((*Event)(nil), "events.Event")
	proto.RegisterType((*CreateEventResponse)(nil), "events.CreateEventResponse")
	proto.RegisterEnum("events.Type", Type_name, Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EventService service

type EventServiceClient interface {
	CreateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*CreateEventResponse, error)
}

type eventServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventServiceClient(cc *grpc.ClientConn) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) CreateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*CreateEventResponse, error) {
	out := new(CreateEventResponse)
	err := grpc.Invoke(ctx, "/events.EventService/CreateEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EventService service

type EventServiceServer interface {
	CreateEvent(context.Context, *Event) (*CreateEventResponse, error)
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/events.EventService/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "events.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _EventService_CreateEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "events.proto",
}

func init() { proto.RegisterFile("events.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 721 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x5f, 0x8f, 0xda, 0x46,
	0x10, 0x8f, 0xb9, 0xc3, 0xe0, 0x01, 0xee, 0x7c, 0x7b, 0x4d, 0x6f, 0x45, 0xfa, 0x80, 0x78, 0x42,
	0x55, 0xc5, 0x55, 0x54, 0x55, 0xd3, 0xe6, 0x09, 0x81, 0xd3, 0xd2, 0xdc, 0x61, 0xb4, 0x5e, 0xd4,
	0xf4, 0xc9, 0x72, 0xf0, 0x84, 0x5a, 0x01, 0xaf, 0xe5, 0x5d, 0xd0, 0xf1, 0x91, 0xfa, 0x75, 0xfa,
	0x89, 0xaa, 0x5d, 0xff, 0xe9, 0x45, 0x8d, 0xc4, 0xdb, 0xfe, 0x66, 0xe6, 0x37, 0x3b, 0xf3, 0x9b,
	0x19, 0xe8, 0xe2, 0x11, 0x53, 0x25, 0xc7, 0x59, 0x2e, 0x94, 0x20, 0x76, 0x81, 0xfa, 0x8e, 0xc2,
	0xd2, 0xd4, 0xef, 0x4a, 0x95, 0x1f, 0x36, 0xaa, 0x44, 0xd7, 0x2a, 0xd9, 0xa3, 0x54, 0xd1, 0x3e,
	0x2b, 0x0d, 0xdf, 0x6c, 0x85, 0xd8, 0xee, 0xf0, 0x3e, 0xca, 0x92, 0xfb, 0x28, 0x4d, 0x85, 0x8a,
	0x54, 0x22, 0xd2, 0x92, 0x3c, 0x8c, 0xc1, 0x09, 0x4e, 0x52, 0xe1, 0xfe, 0x41, 0x6c, 0x89, 0x0b,
	0x17, 0x7b, 0xb9, 0xa5, 0xd6, 0xc0, 0x1a, 0x39, 0x4c, 0x3f, 0xc9, 0x57, 0xd0, 0xdc, 0xe1, 0x11,
	0x77, 0xb4, 0x31, 0xb0, 0x46, 0x3d, 0x56, 0x00, 0x72, 0x0f, 0xf6, 0xc7, 0x04, 0x77, 0xb1, 0xa4,
	0x17, 0x03, 0x6b, 0xd4, 0x99, 0xdc, 0x8d, 0x8b, 0x3f, 0x8a, 0x9c, 0x1f, 0x0e, 0x1f, 0xc7, 0x81,
	0x29, 0x89, 0x95, 0x61, 0xc3, 0xbf, 0x6d, 0x68, 0x7a, 0xba, 0x70, 0x32, 0x80, 0x4b, 0x75, 0xca,
	0xd0, 0xfc, 0x71, 0x35, 0xe9, 0x8e, 0xcb, 0xe6, 0xf8, 0x29, 0x43, 0x66, 0x3c, 0xe4, 0x0a, 0x1a,
	0x49, 0x6c, 0xfe, 0x73, 0x58, 0x23, 0x89, 0x09, 0x85, 0x56, 0xa4, 0x14, 0xee, 0x33, 0x65, 0x7e,
	0xeb, 0xb1, 0x0a, 0x92, 0xd7, 0xe0, 0xd4, 0xcd, 0xd2, 0x4b, 0x53, 0x49, 0xff, 0x7f, 0x95, 0xf0,
	0x2a, 0x82, 0xfd, 0x17, 0x4c, 0x06, 0xd0, 0x94, 0x2a, 0x52, 0x48, 0x9b, 0xa6, 0x0c, 0x18, 0x6b,
	0x35, 0x03, 0x6d, 0x61, 0x85, 0x83, 0xfc, 0x0c, 0x20, 0x55, 0x94, 0xab, 0x50, 0x93, 0xa8, 0x7d,
	0x3e, 0xb9, 0x89, 0xd6, 0x98, 0xfc, 0x08, 0x6d, 0x4c, 0xe3, 0x82, 0xd8, 0x3a, 0x4b, 0x6c, 0x61,
	0x1a, 0x1b, 0xda, 0x77, 0xd0, 0x12, 0x07, 0x95, 0x1d, 0x94, 0xa4, 0xed, 0xc1, 0xc5, 0xa8, 0x33,
	0x21, 0xa6, 0x2a, 0xdf, 0xd8, 0xde, 0x26, 0x3b, 0x7c, 0x10, 0x5b, 0x56, 0x85, 0x90, 0x9f, 0xa0,
	0xbd, 0x47, 0x15, 0xc5, 0x91, 0x8a, 0xa8, 0x63, 0xc2, 0x5f, 0x55, 0x5a, 0x1a, 0xa1, 0xc7, 0x8f,
	0xa5, 0xd7, 0x4b, 0x55, 0x7e, 0x62, 0x75, 0xb0, 0x9e, 0x68, 0x92, 0xc6, 0xf8, 0x44, 0xa1, 0x98,
	0xa8, 0x01, 0xe4, 0x77, 0xb8, 0xc5, 0x27, 0xdc, 0x1c, 0x94, 0xc8, 0xc3, 0x67, 0x7d, 0x77, 0xce,
	0x96, 0x7f, 0x53, 0xd1, 0x82, 0xba, 0xff, 0xb7, 0x50, 0x1b, 0xc3, 0x5a, 0x88, 0xee, 0xd9, 0x4c,
	0xd7, 0x15, 0xc9, 0x2b, 0x05, 0x79, 0x05, 0x0e, 0x3e, 0x25, 0x2a, 0xdc, 0x88, 0x18, 0x69, 0x6f,
	0x60, 0x8d, 0x9a, 0xac, 0xad, 0x0d, 0x33, 0x11, 0x23, 0xb9, 0x83, 0xd6, 0x5f, 0x42, 0xaa, 0x30,
	0xc9, 0xe8, 0x95, 0x59, 0x15, 0x5b, 0xc3, 0x85, 0x19, 0x6d, 0x26, 0x72, 0x25, 0xe9, 0xb5, 0x51,
	0xa5, 0x18, 0xed, 0x4a, 0x5b, 0x58, 0xe1, 0x20, 0x5f, 0x83, 0x2d, 0x55, 0x2c, 0x0e, 0x8a, 0xba,
	0x05, 0xb3, 0x40, 0xa5, 0x1d, 0xf3, 0x9c, 0xde, 0xd4, 0x76, 0xcc, 0x73, 0xf2, 0x3d, 0x80, 0x34,
	0x27, 0x12, 0xee, 0xc4, 0x96, 0x12, 0xd3, 0xc8, 0x4d, 0x25, 0x76, 0x7d, 0x3c, 0xcc, 0x91, 0xd5,
	0xb3, 0xff, 0x06, 0x7a, 0x9f, 0xc9, 0xaf, 0x0f, 0xeb, 0x13, 0x9e, 0xaa, 0xc3, 0xfa, 0x84, 0x27,
	0x3d, 0x86, 0x63, 0xb4, 0x3b, 0x60, 0xb9, 0xe8, 0x05, 0xf8, 0xa5, 0xf1, 0xda, 0x1a, 0xbe, 0x84,
	0xdb, 0x59, 0x8e, 0x91, 0x42, 0x33, 0x47, 0x86, 0x32, 0x13, 0xa9, 0xc4, 0x6f, 0xff, 0xb1, 0xe0,
	0x52, 0x5f, 0x09, 0xe9, 0x40, 0x6b, 0xbd, 0x7c, 0xb7, 0xf4, 0xff, 0x58, 0xba, 0x2f, 0x88, 0x03,
	0xcd, 0x80, 0x4f, 0xb9, 0xe7, 0x5a, 0xe4, 0x0a, 0x20, 0xe0, 0x53, 0xc6, 0x43, 0xbe, 0x78, 0xf4,
	0xdc, 0x06, 0xe9, 0x42, 0xdb, 0x5b, 0xce, 0x0b, 0x74, 0xa1, 0x59, 0xfe, 0x9a, 0xaf, 0xd6, 0x3c,
	0x70, 0x2f, 0xb5, 0xeb, 0xd1, 0xe3, 0xd3, 0xf9, 0x94, 0x4f, 0xdd, 0x26, 0xb9, 0x83, 0x5b, 0xef,
	0xbd, 0x37, 0x5b, 0x73, 0x9f, 0x85, 0xcf, 0x32, 0xd8, 0xe4, 0x25, 0xdc, 0xd4, 0x8e, 0x3a, 0x55,
	0x8b, 0xf4, 0xc0, 0xf1, 0xde, 0x2f, 0x78, 0x38, 0xf3, 0xe7, 0x9e, 0xdb, 0xd6, 0x99, 0x7f, 0xf3,
	0x03, 0x1e, 0x2e, 0x56, 0xae, 0xa3, 0xeb, 0x59, 0xf9, 0x8c, 0x07, 0x2e, 0x10, 0x00, 0x3b, 0xe0,
	0x73, 0x7f, 0xcd, 0xdd, 0x4e, 0xf9, 0xf6, 0x18, 0x73, 0xbb, 0xe6, 0xfd, 0x67, 0xf0, 0xe0, 0xff,
	0xea, 0xf6, 0x26, 0xef, 0xa0, 0x6b, 0xba, 0x0c, 0x30, 0x3f, 0x26, 0x1b, 0x24, 0x6f, 0xa0, 0xf3,
	0xac, 0x77, 0xd2, 0xfb, 0x6c, 0xa5, 0xfb, 0xf5, 0x86, 0x7f, 0x41, 0x9f, 0xe1, 0x8b, 0x0f, 0xb6,
	0x59, 0xaa, 0x1f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x05, 0x82, 0xcf, 0x8b, 0x31, 0x05, 0x00,
	0x00,
}
