baseURL: https://ohsu-comp-bio.github.io/funnel/
canonifyURLs: true
languageCode: en-us
title: Funnel

menu:
  main:

  - name: Reference
    url: https://godoc.org/github.com/ohsu-comp-bio/funnel
    weight: 30
